version: "3"
services:
  kafka:
    image: 'bitnami/kafka:3.6.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,CLIENT://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,CLIENT://kafka:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    volumes:
      - kafka_data:/bitnami/kafka
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  ksqldb:
    image: 'confluentinc/ksqldb-server:0.29.0'
    ports:
      - '8088:8088'
    volumes:
      - './sql:/etc/sql:ro'
    environment:
      - KSQL_BOOTSTRAP_SERVERS=kafka:29092
      - KSQL_LISTENERS=http://0.0.0.0:8088/
      - KSQL_KSQL_SERVICE_ID=ksql_service_2_
      - KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE=true
      - KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE=true
      - KSQL_KSQL_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      # Telemetrie deaktivieren
      - KSQL_CONFLUENT_SUPPORT_METRICS_ENABLE=false
      - KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR=1
      - KSQL_KSQL_LOGGING_PROCESSING_STREAM_REPLICATION_FACTOR=1
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_started
    restart: unless-stopped

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    ports:
      - '8081:8081'
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:29092
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      # Retry-Konfiguration für bessere Stabilität
      - SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS=10000
      - SCHEMA_REGISTRY_KAFKASTORE_INIT_TIMEOUT_MS=60000
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS_RETRY_ATTEMPTS=5
      # Telemetrie deaktivieren
      - SCHEMA_REGISTRY_CONFLUENT_SUPPORT_METRICS_ENABLE=false
    restart: unless-stopped

volumes:
  kafka_data: